# Generated by Django 5.0.3 on 2024-03-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_accessories',
            new_name='ProductsAccessories',
        ),
        migrations.RenameModel(
            old_name='Products_bedroom',
            new_name='ProductsBedroom',
        ),
        migrations.RenameModel(
            old_name='Products_decor',
            new_name='ProductsDecor',
        ),
        migrations.RenameModel(
            old_name='Products_kitchen',
            new_name='ProductsKitchen',
        ),
        migrations.RenameModel(
            old_name='Products_livingroom',
            new_name='ProductsLivingRoom',
        ),
        migrations.RenameModel(
            old_name='Products_office',
            new_name='ProductsOffice',
        ),
    ]
