# Generated by Django 5.0.3 on 2024-04-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_productskitchen_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-id']},
        ),
    ]
