# Generated by Django 5.0.3 on 2024-03-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_products_accessories_productsaccessories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsKitchen',
            new_name='Products',
        ),
        migrations.RemoveField(
            model_name='productsbedroom',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsdecor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productslivingroom',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsoffice',
            name='category',
        ),
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
        migrations.DeleteModel(
            name='ProductsAccessories',
        ),
        migrations.DeleteModel(
            name='ProductsBedroom',
        ),
        migrations.DeleteModel(
            name='ProductsDecor',
        ),
        migrations.DeleteModel(
            name='ProductsLivingRoom',
        ),
        migrations.DeleteModel(
            name='ProductsOffice',
        ),
    ]
